### ISSUE TITLE
Error with windows pip install

### ISSUE THREAD

**Issue by libxx1** [raspberrypilearning/amazing-image-identifier#7]
URL: /en/projects/amazing-image-identifier/1

Hey! When running on windows with a fresh install of python 3.9.3 and pip 21.0.1  the pip install -r requirements.txt will fail when installing kiwisolver. This was because wheel was not found. Installing wheel fixed it for me :)

**Comment by libxx1** [comment]
A couple more issues have come in for this project. @PhilipHarney can you take a look please and see if there are any problems with the project. Happy for you to close if all ok. 

URL: /en/projects/amazing-image-identifier/2

Running into below issues:
XXX:~/amazing_image_identifier $ python3 project.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/lib/python3/dist-packages/guizero/PushButton.py", line 146, in _command_callback
    self._command()
  File "project.py", line 88, in update_picture
    pic = app.select_file()
AttributeError: 'App' object has no attribute 'select_file'


URL: /en/projects/amazing-image-identifier/5

ImportError: `load_weights` requires h5py when loading weights from HDF5.
network.py, line 1252

**Comment by libxx1** [comment]
Hey @PhilipHarney can you have a look at these please. If this project is going to be replaced or if the issue will be fixed by the new changes can you close it. Ta.
